### ISSUE TITLE
The IM failed to set the cardinality spec strictly for the ‘Inventory.Uniformly_Sampled’ attribute

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS/pds4-information-model#478] opened 2022-05-13 06:39 UTC
## 🐛 Describe the bug identified during I&T
The IM failed to set the cardinality spec strictly for the ‘Inventory.Uniformly_Sampled’ attribute, which is required in [CCB-335 to disallow usage (see "Requested Changes" section <span>#</span>4](https://pds-jira.jpl.nasa.gov/browse/CCB-335) -- "Prohibit inclusion of Inventory.Uniformly_Sampled (for example, by setting its cardinality to 0..0)".

This was found during testing of [pds4-information-model#453](https://github.com/NASA-PDS/pds4-information-model/issues/453) ticket.

## 🥼 Related Test Case(s)
[IM.9](https://pds-engineering.jpl.nasa.gov/sites/default/files/documents/Build%20Deliverables/Build%2012.1%20I%26T%20Deliverables/Release%20Build%2012.1%20Test%20Plan.v6.20220407.pdf)

## 🔁 : Related issues
[pds4-information-model#453](https://github.com/NASA-PDS/pds4-information-model/issues/453)
[pds4-information-model#454](https://github.com/NASA-PDS/pds4-information-model/issues/454)
[CCB-335](https://pds-jira.jpl.nasa.gov/browse/CCB-335)

---
### 📜 To Reproduce
1. Execute `cat testdata/PDS4_PDS_1I00.sch | grep -A25 -B3 -n -i 'Uniformly_sampled' | grep '0.'`
2. Note that there is no cardinality setting for 0 to 0. 
3. Verify by examining the [Abridged v1.18.0 Data Dictionary](https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1I00.html) to note that the [Inventory Class still maintains a cardinality of (0..1)](https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1I00.html#d5e8249) -- which it shouldn't.

5. See error

### 🕵️ Expected behavior
The cardinality for `Inventory.uniformly_sampled` is `(0..0)` in all data documents, both specifications and concrete implementations.  

### 📚 Version of Software Used
pds4-information-model-ontology version 14.0.1

### 🩺 Test Data / Additional context
[Test Data](https://github.com/NASA-PDS/pds4-information-model/files/8674004/testdata.zip)

###  🏞Screenshots
Please see attached screenshots.
![Screen Shot 2022-05-12 at 11 34 06 PM](https://user-images.githubusercontent.com/52300928/168225306-73379074-5a8f-4491-a616-201c5b49cce7.png)

### 🖥 System Info
 - OS: Mac OS X 11.5.6
 - Browser: Chrome
 - Version 101.0.4951.64

---

**Comment by jordanpadams** [comment] 2022-05-13 15:53
@jshughes can you take a look at this ASAP? We should probably try to get this fix into the build if at all possible.

**Comment by jshughes** [comment] 2022-05-13 16:41
Richard Chen also found this issue. However the decision was made to table the implementation of items 2-5 of this SCR and possibly implement them in the next build. More DDWG discussion is necessary for these minor changes.

Rationale: this SCR was finally approved after the DDWG deadline This allowed only a small amount of time to implement all five items.  The key item (1) was implemented. The problem is that implementation of the other items are not simple and need further discussion. 

For example in item 3 there is no standard value list for "name".

For item 4, "Prohibit inclusion of Inventory.Uniformly_Sampled (for example, by setting its cardinality to 0..0)", cannot be implemented since XML schema would need to have a new compositeType since  <Inventory.Uniformly_Sampled> is inherited and cannot be changed.  So the most reasonable implementation is a schematron rule, if this is necessary. Finally this is a "polishing the cannon ball" fix since no sane Inventory provider would use a Uniformly_Sampled class.

**Comment by jordanpadams** [comment] 2022-05-16 18:42
closing as invalid

**Closed** 2022-05-17 20:17 UTC
Labels: bug, invalid, I&T, B12.1, sprint-backlog, s.medium
