### ISSUE TITLE
LDDTool does not generate the correct namespace for PSA dictionaries

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/pds4-information-model#301] opened 2021-01-26 16:20 UTC
**Describe the bug**
The PSA cross mission dictionary uses a registered namespace and the initial part of the Ingest_LDD class reads:

```
<Ingest_LDD xmlns="http://pds.nasa.gov/pds4/pds/v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pds.nasa.gov/pds4/pds/v1 https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1F00.xsd">
    <name>PSA Local Data Dictionary</name>
    <ldd_version_id>1.3.0.0</ldd_version_id>
    <dictionary_type>Mission</dictionary_type>
    <full_name>M.S. Bentley</full_name>
    <steward_id>psa</steward_id>
    <namespace_id>psa</namespace_id>
```
The dictionary generated by LDDTool 12.1.0 and the command `lddtool -lp <PSA Ingest file>` results in:

`xmlns:psa="http://psa.esa.int/mission/psa/v1"` in the schema and
`<sch:ns uri="http://pds.nasa.gov/pds4/mission/psa/v1" prefix="psa"/>` in the Schematron

Neither are correct, and the namespace should be: `http://psa.esa.int/psa/v1"` as listed in the namespace registry: 
https://pds.jpl.nasa.gov/datastandards/schema/pds-namespace-registry.pdf

Issue #303 contains Ingest files that can be used for testing.

**Expected behavior**

The registered namespace should be used, or else a method provided to specify the namespace in the Ingest file.

This is an issue for PSA mission and instrument dictionaries as well.

**Version of Software Used**
```
LDDTool Version: 12.1.0
Built with IM Version: 1.15.0.0
Build Date: 2021-01-11 12:52:30
Configured IM Versions: [1F00, 1E00, 1D00, 1C00, 1B10, 1B00]
```

**Desktop (please complete the following information):**
 - OS: linux
 - Version: ubuntu 20.04

**Comment by jshughes** [comment] 2021-01-27 16:00
This issue has been raised before but it has never been officially resolved. Historically any LDD with "Mission" as the value of the attribute <dictionary_type> was to have the term "mission" inserted into its namespace URL during the generation of the XML Schema and Schematron files.  Recently a proposal to remove this rule never made it past discussion. The original intent of the rule was more for organizing or grouping mission LDDs together.

Given the current situation, technical solutions include:
1) add a new command-line option to indicate that the rule should be ignored,
2) add a flag to Ingest_LDD to indicate that the rule should be ignored,
3) specify the namespace in the Ingest file.

The impact of this change on the overall system, however, should be discussed by the DDWG.

**Comment by jordanpadams** [comment] 2021-01-27 16:23
duplicate of #304

**Comment by jordanpadams** [comment] 2021-01-27 16:36
@msbentley we think this is fixed with #304 fix. please verify

**Comment by msbentley** [comment] 2021-01-28 17:02
Hi @jordanpadams I'm not sure that anything affecting this ticket has been resolved by #304?

As @jshughes points out there is discussion needed here.

But I would flag that the fact that the namespace URI written to the XSD and SCH being different looks like a bug, no? Even if they are wrong, I would expect them to be the same. Also with the snapshot I have:

`<sch:ns uri="http://pds.nasa.gov/pds4/mission/psa/v1" prefix="psa"/>`
vs
`xmlns:psa="http://psa.esa.int/mission/psa/v1"`

**Comment by jordanpadams** [comment] 2021-01-28 17:54
@msbentley copy. i misunderstood the issue here. will leave open.

@jshughes since this is something that needs discussion, should we move out? or something that can be discussed in the near-term?

**Comment by rchenatjpl** [comment] 2021-06-03 06:41
@jshughes @jordanpadams 
If I've followed this correctly (very possibly not), psa: is supposed to be http://psa.esa.int/psa/v1, but I'm seeing mission/ inserted in there, i.e. http://psa.esa.int/mission/psa/v1 when run on Mark's input file in #303.

% lddtool -v
LDDTool Version: 13.1.0-SNAPSHOT
Built with IM Version: 1.16.0.0
Build Date: 2021-05-20 15:08:21
Configured IM Versions: [1G00, 1F00, 1E00, 1D00, 1C00, 1B10, 1B00]
% lddtool -pl Ingest_PDS4_PSA_1300.xml
[chop]
% grep psa/v1 PDS4_PSA_1G00_1300.*
PDS4_PSA_1G00_1300.sch:  <sch:ns uri="http://psa.esa.int/mission/psa/v1" prefix="psa"/>
PDS4_PSA_1G00_1300.xsd:    targetNamespace="http://psa.esa.int/mission/psa/v1"
PDS4_PSA_1G00_1300.xsd:    xmlns:psa="http://psa.esa.int/mission/psa/v1"

**Comment by jshughes** [comment] 2021-06-03 12:53
@msbentley can confirm but my understanding is that this is correct. PSA has no Discipline level LDDs.

**Comment by msbentley** [comment] 2021-06-03 13:02
Hi @rchenatjpl @jshughes - indeed there should _NOT_ be any `/mission/` inserted into the PSA namespaces. I have to say I tested so many snapshots etc. of LDDTool that I would have to download the latest and test again to be 100% sure what the current behaviour is...

**Comment by jshughes** [comment] 2021-06-03 14:53
Hi @msbentley @rchenatjpl @jordanpadams 

Yes, there have been quite a lot of updates to LDDTool this build. I am not sure what happened in this case, however here is what we know and a proposal.

1) All PSA LDD Ingest_LDD files have <dictionary_type> = Mission. 
2) It seems that all these Ingest_LDD files also have <steward_id> = psa.
3) In the LDDTool config.properties file, all PSA entries have <sysBundleName> set to something besides the default, "system_bundle".
4) By default LDDTool inserts "Mission" into the namespaces for all LDDs where <dictionary_type> = Mission. 

Proposal.
1) if item 2 above is true, then for these Ingest_LDD files do not insert "Mission" into the namespace, regardless of the value of <dictionary_type>.

 - alternate proposal:

2) If item2 is not true, then when is <sysBundleName> set to something besides the default, do not insert "Mission" into the namespace, regardless of the value of <dictionary_type>.

**Comment by jordanpadams** [comment] 2021-06-03 15:18
@jshughes what do we think about just adding a new flag like `--exclude-mission-from-url` or a shortened `-M`?

**Comment by jordanpadams** [comment] 2021-06-03 15:20
We can put this logic into the code, but we just need to make sure we document this appropriately in the description for the Mission dictionary_type value. I could see us totally forgetting why PSA LDDs output differently than everything else even though they run LDDTool the exact same way.

**Comment by jshughes** [comment] 2021-06-03 15:52
To @msbentley @rchenatjpl @jordanpadams

After looking deeper into the code a flag already exists for this purpose, "-d", and is currently active. For some reason, however, it is not displayed in the list of options. The flag "-M" has previously been used and then deprecated. Given a successful test, it seems that the only change needed is to let the flag be displayed in the list of options. 

Also the flag option better addresses the situation where another steward decides to follow the precedent set by PSA.

**Closed by jshughes** 2021-06-03 15:52 UTC
Labels: B11.1, I&T, bug, im

**Comment by jordanpadams** [comment] 2021-06-03 17:05
updated the PR with this new flag as well

**Comment by jordanpadams** [comment] 2021-06-03 17:07
@jshughes can you push a PR for this? or send me the update and I can add it to the latest tagged release?
