### ISSUE TITLE
add new namespaces for juice mission

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/pds4-information-model#804] opened 2024-08-06 18:07 UTC
### Namespace ID Requested

Added the following namespace ids to the Namespace Registry and the config.properties file.

juice
juice_gala
juice_janus
juice_jmc
juice_majis
juice_navcam
juice_rime
juice_swi
juice_uvs
juice_radem
juice_3gm
juice_haa
juice_jmag
juice_rpwi
juice_pephi
juice_peplo
juice_pride

### Associated Namespace Details

Added namespace details for the "juice" mission from (https://s2e2.cosmos.esa.int/confluence/display/PSAPUB1/PSA+namespace+registry)

Resolves NASA-PDS/pds4-information-model#803

### Engineering Details

- [x] @jshughes update namespace registry

**Comment by jshughes** [comment] 2024-08-06 18:25
@jordanpadams This issue was opened in error. It can be ignored. 
Issue #805 resolved Issue #803.

**Comment by jordanpadams** [comment] 2024-08-06 20:25
duplicate of #803

**Closed by jordanpadams** 2024-08-06 20:25 UTC
Labels: enhancement, B15.0, p.must-have, sprint-backlog
